name: GHGEAT
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - attrs==25.4.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - greenlet==3.2.4
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mordred==1.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==2.8.8
      - numba==0.62.1
      - numpy==1.26.4
      - optuna==4.6.0
      - packaging==25.0
      - pandas==2.3.3
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - pillow==12.0.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pycparser==2.23
      - pyparsing==3.2.5
      - pypdfium2==5.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.1
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - shap==0.49.1
      - six==1.17.0
      - slicer==0.0.8
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0+cu128
      - torch-cluster==1.6.3+pt28cu128
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt28cu128
      - torch-sparse==0.6.18+pt28cu128
      - torch-spline-conv==1.2.2+pt28cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0

